// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package codexauth

import (
	"context"
	"github.com/tursom/turapis/internal/email"
	"sync"
	"time"
)

// EmailProviderMock is a mock implementation of email.EmailProvider.
//
//	func TestSomethingThatUsesEmailProvider(t *testing.T) {
//
//		// make and configure a mocked email.EmailProvider
//		mockedEmailProvider := &EmailProviderMock{
//			CreateInboxFunc: func(ctx context.Context) (*email.InboxInfo, error) {
//				panic("mock out the CreateInbox method")
//			},
//			CreateInboxWithAliasFunc: func(ctx context.Context, alias string, domain string) (*email.InboxInfo, error) {
//				panic("mock out the CreateInboxWithAlias method")
//			},
//			GetMessageFunc: func(ctx context.Context, inbox *email.InboxInfo, messageID string) (*email.EmailMessage, error) {
//				panic("mock out the GetMessage method")
//			},
//			GetMessagesFunc: func(ctx context.Context, inbox *email.InboxInfo) ([]email.EmailMessage, error) {
//				panic("mock out the GetMessages method")
//			},
//			NameFunc: func() string {
//				panic("mock out the Name method")
//			},
//			SupportsReuseFunc: func() bool {
//				panic("mock out the SupportsReuse method")
//			},
//			WaitForEmailFunc: func(ctx context.Context, inbox *email.InboxInfo, timeout time.Duration, predicate func(*email.EmailMessage) bool) (*email.EmailMessage, error) {
//				panic("mock out the WaitForEmail method")
//			},
//		}
//
//		// use mockedEmailProvider in code that requires email.EmailProvider
//		// and then make assertions.
//
//	}
type EmailProviderMock struct {
	// CreateInboxFunc mocks the CreateInbox method.
	CreateInboxFunc func(ctx context.Context) (*email.InboxInfo, error)

	// CreateInboxWithAliasFunc mocks the CreateInboxWithAlias method.
	CreateInboxWithAliasFunc func(ctx context.Context, alias string, domain string) (*email.InboxInfo, error)

	// GetMessageFunc mocks the GetMessage method.
	GetMessageFunc func(ctx context.Context, inbox *email.InboxInfo, messageID string) (*email.EmailMessage, error)

	// GetMessagesFunc mocks the GetMessages method.
	GetMessagesFunc func(ctx context.Context, inbox *email.InboxInfo) ([]email.EmailMessage, error)

	// NameFunc mocks the Name method.
	NameFunc func() string

	// SupportsReuseFunc mocks the SupportsReuse method.
	SupportsReuseFunc func() bool

	// WaitForEmailFunc mocks the WaitForEmail method.
	WaitForEmailFunc func(ctx context.Context, inbox *email.InboxInfo, timeout time.Duration, predicate func(*email.EmailMessage) bool) (*email.EmailMessage, error)

	// calls tracks calls to the methods.
	calls struct {
		// CreateInbox holds details about calls to the CreateInbox method.
		CreateInbox []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// CreateInboxWithAlias holds details about calls to the CreateInboxWithAlias method.
		CreateInboxWithAlias []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Alias is the alias argument value.
			Alias string
			// Domain is the domain argument value.
			Domain string
		}
		// GetMessage holds details about calls to the GetMessage method.
		GetMessage []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Inbox is the inbox argument value.
			Inbox *email.InboxInfo
			// MessageID is the messageID argument value.
			MessageID string
		}
		// GetMessages holds details about calls to the GetMessages method.
		GetMessages []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Inbox is the inbox argument value.
			Inbox *email.InboxInfo
		}
		// Name holds details about calls to the Name method.
		Name []struct {
		}
		// SupportsReuse holds details about calls to the SupportsReuse method.
		SupportsReuse []struct {
		}
		// WaitForEmail holds details about calls to the WaitForEmail method.
		WaitForEmail []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Inbox is the inbox argument value.
			Inbox *email.InboxInfo
			// Timeout is the timeout argument value.
			Timeout time.Duration
			// Predicate is the predicate argument value.
			Predicate func(*email.EmailMessage) bool
		}
	}
	lockCreateInbox          sync.RWMutex
	lockCreateInboxWithAlias sync.RWMutex
	lockGetMessage           sync.RWMutex
	lockGetMessages          sync.RWMutex
	lockName                 sync.RWMutex
	lockSupportsReuse        sync.RWMutex
	lockWaitForEmail         sync.RWMutex
}

// CreateInbox calls CreateInboxFunc.
func (mock *EmailProviderMock) CreateInbox(ctx context.Context) (*email.InboxInfo, error) {
	if mock.CreateInboxFunc == nil {
		panic("EmailProviderMock.CreateInboxFunc: method is nil but EmailProvider.CreateInbox was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockCreateInbox.Lock()
	mock.calls.CreateInbox = append(mock.calls.CreateInbox, callInfo)
	mock.lockCreateInbox.Unlock()
	return mock.CreateInboxFunc(ctx)
}

// CreateInboxCalls gets all the calls that were made to CreateInbox.
// Check the length with:
//
//	len(mockedEmailProvider.CreateInboxCalls())
func (mock *EmailProviderMock) CreateInboxCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockCreateInbox.RLock()
	calls = mock.calls.CreateInbox
	mock.lockCreateInbox.RUnlock()
	return calls
}

// CreateInboxWithAlias calls CreateInboxWithAliasFunc.
func (mock *EmailProviderMock) CreateInboxWithAlias(ctx context.Context, alias string, domain string) (*email.InboxInfo, error) {
	if mock.CreateInboxWithAliasFunc == nil {
		panic("EmailProviderMock.CreateInboxWithAliasFunc: method is nil but EmailProvider.CreateInboxWithAlias was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Alias  string
		Domain string
	}{
		Ctx:    ctx,
		Alias:  alias,
		Domain: domain,
	}
	mock.lockCreateInboxWithAlias.Lock()
	mock.calls.CreateInboxWithAlias = append(mock.calls.CreateInboxWithAlias, callInfo)
	mock.lockCreateInboxWithAlias.Unlock()
	return mock.CreateInboxWithAliasFunc(ctx, alias, domain)
}

// CreateInboxWithAliasCalls gets all the calls that were made to CreateInboxWithAlias.
// Check the length with:
//
//	len(mockedEmailProvider.CreateInboxWithAliasCalls())
func (mock *EmailProviderMock) CreateInboxWithAliasCalls() []struct {
	Ctx    context.Context
	Alias  string
	Domain string
} {
	var calls []struct {
		Ctx    context.Context
		Alias  string
		Domain string
	}
	mock.lockCreateInboxWithAlias.RLock()
	calls = mock.calls.CreateInboxWithAlias
	mock.lockCreateInboxWithAlias.RUnlock()
	return calls
}

// GetMessage calls GetMessageFunc.
func (mock *EmailProviderMock) GetMessage(ctx context.Context, inbox *email.InboxInfo, messageID string) (*email.EmailMessage, error) {
	if mock.GetMessageFunc == nil {
		panic("EmailProviderMock.GetMessageFunc: method is nil but EmailProvider.GetMessage was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Inbox     *email.InboxInfo
		MessageID string
	}{
		Ctx:       ctx,
		Inbox:     inbox,
		MessageID: messageID,
	}
	mock.lockGetMessage.Lock()
	mock.calls.GetMessage = append(mock.calls.GetMessage, callInfo)
	mock.lockGetMessage.Unlock()
	return mock.GetMessageFunc(ctx, inbox, messageID)
}

// GetMessageCalls gets all the calls that were made to GetMessage.
// Check the length with:
//
//	len(mockedEmailProvider.GetMessageCalls())
func (mock *EmailProviderMock) GetMessageCalls() []struct {
	Ctx       context.Context
	Inbox     *email.InboxInfo
	MessageID string
} {
	var calls []struct {
		Ctx       context.Context
		Inbox     *email.InboxInfo
		MessageID string
	}
	mock.lockGetMessage.RLock()
	calls = mock.calls.GetMessage
	mock.lockGetMessage.RUnlock()
	return calls
}

// GetMessages calls GetMessagesFunc.
func (mock *EmailProviderMock) GetMessages(ctx context.Context, inbox *email.InboxInfo) ([]email.EmailMessage, error) {
	if mock.GetMessagesFunc == nil {
		panic("EmailProviderMock.GetMessagesFunc: method is nil but EmailProvider.GetMessages was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Inbox *email.InboxInfo
	}{
		Ctx:   ctx,
		Inbox: inbox,
	}
	mock.lockGetMessages.Lock()
	mock.calls.GetMessages = append(mock.calls.GetMessages, callInfo)
	mock.lockGetMessages.Unlock()
	return mock.GetMessagesFunc(ctx, inbox)
}

// GetMessagesCalls gets all the calls that were made to GetMessages.
// Check the length with:
//
//	len(mockedEmailProvider.GetMessagesCalls())
func (mock *EmailProviderMock) GetMessagesCalls() []struct {
	Ctx   context.Context
	Inbox *email.InboxInfo
} {
	var calls []struct {
		Ctx   context.Context
		Inbox *email.InboxInfo
	}
	mock.lockGetMessages.RLock()
	calls = mock.calls.GetMessages
	mock.lockGetMessages.RUnlock()
	return calls
}

// Name calls NameFunc.
func (mock *EmailProviderMock) Name() string {
	if mock.NameFunc == nil {
		panic("EmailProviderMock.NameFunc: method is nil but EmailProvider.Name was just called")
	}
	callInfo := struct {
	}{}
	mock.lockName.Lock()
	mock.calls.Name = append(mock.calls.Name, callInfo)
	mock.lockName.Unlock()
	return mock.NameFunc()
}

// NameCalls gets all the calls that were made to Name.
// Check the length with:
//
//	len(mockedEmailProvider.NameCalls())
func (mock *EmailProviderMock) NameCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockName.RLock()
	calls = mock.calls.Name
	mock.lockName.RUnlock()
	return calls
}

// SupportsReuse calls SupportsReuseFunc.
func (mock *EmailProviderMock) SupportsReuse() bool {
	if mock.SupportsReuseFunc == nil {
		panic("EmailProviderMock.SupportsReuseFunc: method is nil but EmailProvider.SupportsReuse was just called")
	}
	callInfo := struct {
	}{}
	mock.lockSupportsReuse.Lock()
	mock.calls.SupportsReuse = append(mock.calls.SupportsReuse, callInfo)
	mock.lockSupportsReuse.Unlock()
	return mock.SupportsReuseFunc()
}

// SupportsReuseCalls gets all the calls that were made to SupportsReuse.
// Check the length with:
//
//	len(mockedEmailProvider.SupportsReuseCalls())
func (mock *EmailProviderMock) SupportsReuseCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockSupportsReuse.RLock()
	calls = mock.calls.SupportsReuse
	mock.lockSupportsReuse.RUnlock()
	return calls
}

// WaitForEmail calls WaitForEmailFunc.
func (mock *EmailProviderMock) WaitForEmail(ctx context.Context, inbox *email.InboxInfo, timeout time.Duration, predicate func(*email.EmailMessage) bool) (*email.EmailMessage, error) {
	if mock.WaitForEmailFunc == nil {
		panic("EmailProviderMock.WaitForEmailFunc: method is nil but EmailProvider.WaitForEmail was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Inbox     *email.InboxInfo
		Timeout   time.Duration
		Predicate func(*email.EmailMessage) bool
	}{
		Ctx:       ctx,
		Inbox:     inbox,
		Timeout:   timeout,
		Predicate: predicate,
	}
	mock.lockWaitForEmail.Lock()
	mock.calls.WaitForEmail = append(mock.calls.WaitForEmail, callInfo)
	mock.lockWaitForEmail.Unlock()
	return mock.WaitForEmailFunc(ctx, inbox, timeout, predicate)
}

// WaitForEmailCalls gets all the calls that were made to WaitForEmail.
// Check the length with:
//
//	len(mockedEmailProvider.WaitForEmailCalls())
func (mock *EmailProviderMock) WaitForEmailCalls() []struct {
	Ctx       context.Context
	Inbox     *email.InboxInfo
	Timeout   time.Duration
	Predicate func(*email.EmailMessage) bool
} {
	var calls []struct {
		Ctx       context.Context
		Inbox     *email.InboxInfo
		Timeout   time.Duration
		Predicate func(*email.EmailMessage) bool
	}
	mock.lockWaitForEmail.RLock()
	calls = mock.calls.WaitForEmail
	mock.lockWaitForEmail.RUnlock()
	return calls
}
