// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package codexauth

import (
	"context"
	"sync"
)

// RegFlowRunnerMock is a mock implementation of RegFlowRunner.
//
//	func TestSomethingThatUsesRegFlowRunner(t *testing.T) {
//
//		// make and configure a mocked RegFlowRunner
//		mockedRegFlowRunner := &RegFlowRunnerMock{
//			RunRegisterFunc: func(ctx context.Context) (*FlowResult, *EmailCredential, error) {
//				panic("mock out the RunRegister method")
//			},
//			RunReloginFunc: func(ctx context.Context, ec *EmailCredential) (*FlowResult, error) {
//				panic("mock out the RunRelogin method")
//			},
//		}
//
//		// use mockedRegFlowRunner in code that requires RegFlowRunner
//		// and then make assertions.
//
//	}
type RegFlowRunnerMock struct {
	// RunRegisterFunc mocks the RunRegister method.
	RunRegisterFunc func(ctx context.Context) (*FlowResult, *EmailCredential, error)

	// RunReloginFunc mocks the RunRelogin method.
	RunReloginFunc func(ctx context.Context, ec *EmailCredential) (*FlowResult, error)

	// calls tracks calls to the methods.
	calls struct {
		// RunRegister holds details about calls to the RunRegister method.
		RunRegister []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// RunRelogin holds details about calls to the RunRelogin method.
		RunRelogin []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Ec is the ec argument value.
			Ec *EmailCredential
		}
	}
	lockRunRegister sync.RWMutex
	lockRunRelogin  sync.RWMutex
}

// RunRegister calls RunRegisterFunc.
func (mock *RegFlowRunnerMock) RunRegister(ctx context.Context) (*FlowResult, *EmailCredential, error) {
	if mock.RunRegisterFunc == nil {
		panic("RegFlowRunnerMock.RunRegisterFunc: method is nil but RegFlowRunner.RunRegister was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockRunRegister.Lock()
	mock.calls.RunRegister = append(mock.calls.RunRegister, callInfo)
	mock.lockRunRegister.Unlock()
	return mock.RunRegisterFunc(ctx)
}

// RunRegisterCalls gets all the calls that were made to RunRegister.
// Check the length with:
//
//	len(mockedRegFlowRunner.RunRegisterCalls())
func (mock *RegFlowRunnerMock) RunRegisterCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockRunRegister.RLock()
	calls = mock.calls.RunRegister
	mock.lockRunRegister.RUnlock()
	return calls
}

// RunRelogin calls RunReloginFunc.
func (mock *RegFlowRunnerMock) RunRelogin(ctx context.Context, ec *EmailCredential) (*FlowResult, error) {
	if mock.RunReloginFunc == nil {
		panic("RegFlowRunnerMock.RunReloginFunc: method is nil but RegFlowRunner.RunRelogin was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Ec  *EmailCredential
	}{
		Ctx: ctx,
		Ec:  ec,
	}
	mock.lockRunRelogin.Lock()
	mock.calls.RunRelogin = append(mock.calls.RunRelogin, callInfo)
	mock.lockRunRelogin.Unlock()
	return mock.RunReloginFunc(ctx, ec)
}

// RunReloginCalls gets all the calls that were made to RunRelogin.
// Check the length with:
//
//	len(mockedRegFlowRunner.RunReloginCalls())
func (mock *RegFlowRunnerMock) RunReloginCalls() []struct {
	Ctx context.Context
	Ec  *EmailCredential
} {
	var calls []struct {
		Ctx context.Context
		Ec  *EmailCredential
	}
	mock.lockRunRelogin.RLock()
	calls = mock.calls.RunRelogin
	mock.lockRunRelogin.RUnlock()
	return calls
}
