// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package codexauth

import (
	"encoding/json"
	"github.com/tursom/turapis/internal/config"
	"sync"
)

// RegistryStoreMock is a mock implementation of RegistryStore.
//
//	func TestSomethingThatUsesRegistryStore(t *testing.T) {
//
//		// make and configure a mocked RegistryStore
//		mockedRegistryStore := &RegistryStoreMock{
//			CreateCodexAccountFunc: func(a *config.CodexAccount) error {
//				panic("mock out the CreateCodexAccount method")
//			},
//			CreateProviderFromSiteFunc: func(siteID int, nameOverride string, apiKey string, oauthJSON json.RawMessage) (*config.Provider, int, error) {
//				panic("mock out the CreateProviderFromSite method")
//			},
//			DeleteCodexAccountFunc: func(id int) error {
//				panic("mock out the DeleteCodexAccount method")
//			},
//			DeleteProviderFunc: func(id int) error {
//				panic("mock out the DeleteProvider method")
//			},
//			FindCodexAccountByProviderIDFunc: func(providerID int) (*config.CodexAccount, error) {
//				panic("mock out the FindCodexAccountByProviderID method")
//			},
//			GetCodexAccountFunc: func(id int) (*config.CodexAccount, error) {
//				panic("mock out the GetCodexAccount method")
//			},
//			GetCodexAccountByAccountIDFunc: func(accountID string) (*config.CodexAccount, error) {
//				panic("mock out the GetCodexAccountByAccountID method")
//			},
//			GetProviderAPIKeyFunc: func(id int) (string, error) {
//				panic("mock out the GetProviderAPIKey method")
//			},
//			ListCodexAccountsFunc: func() ([]config.CodexAccount, error) {
//				panic("mock out the ListCodexAccounts method")
//			},
//			UpdateCodexAccountFunc: func(a *config.CodexAccount) error {
//				panic("mock out the UpdateCodexAccount method")
//			},
//			UpdateCodexAccountHealthFunc: func(id int) error {
//				panic("mock out the UpdateCodexAccountHealth method")
//			},
//			UpdateCodexAccountRefreshFunc: func(id int) error {
//				panic("mock out the UpdateCodexAccountRefresh method")
//			},
//			UpdateCodexAccountStatusFunc: func(id int, status string, errorMsg string) error {
//				panic("mock out the UpdateCodexAccountStatus method")
//			},
//			UpdateProviderAPIKeyFunc: func(id int, apiKey string) error {
//				panic("mock out the UpdateProviderAPIKey method")
//			},
//		}
//
//		// use mockedRegistryStore in code that requires RegistryStore
//		// and then make assertions.
//
//	}
type RegistryStoreMock struct {
	// CreateCodexAccountFunc mocks the CreateCodexAccount method.
	CreateCodexAccountFunc func(a *config.CodexAccount) error

	// CreateProviderFromSiteFunc mocks the CreateProviderFromSite method.
	CreateProviderFromSiteFunc func(siteID int, nameOverride string, apiKey string, oauthJSON json.RawMessage) (*config.Provider, int, error)

	// DeleteCodexAccountFunc mocks the DeleteCodexAccount method.
	DeleteCodexAccountFunc func(id int) error

	// DeleteProviderFunc mocks the DeleteProvider method.
	DeleteProviderFunc func(id int) error

	// FindCodexAccountByProviderIDFunc mocks the FindCodexAccountByProviderID method.
	FindCodexAccountByProviderIDFunc func(providerID int) (*config.CodexAccount, error)

	// GetCodexAccountFunc mocks the GetCodexAccount method.
	GetCodexAccountFunc func(id int) (*config.CodexAccount, error)

	// GetCodexAccountByAccountIDFunc mocks the GetCodexAccountByAccountID method.
	GetCodexAccountByAccountIDFunc func(accountID string) (*config.CodexAccount, error)

	// GetProviderAPIKeyFunc mocks the GetProviderAPIKey method.
	GetProviderAPIKeyFunc func(id int) (string, error)

	// ListCodexAccountsFunc mocks the ListCodexAccounts method.
	ListCodexAccountsFunc func() ([]config.CodexAccount, error)

	// UpdateCodexAccountFunc mocks the UpdateCodexAccount method.
	UpdateCodexAccountFunc func(a *config.CodexAccount) error

	// UpdateCodexAccountHealthFunc mocks the UpdateCodexAccountHealth method.
	UpdateCodexAccountHealthFunc func(id int) error

	// UpdateCodexAccountRefreshFunc mocks the UpdateCodexAccountRefresh method.
	UpdateCodexAccountRefreshFunc func(id int) error

	// UpdateCodexAccountStatusFunc mocks the UpdateCodexAccountStatus method.
	UpdateCodexAccountStatusFunc func(id int, status string, errorMsg string) error

	// UpdateProviderAPIKeyFunc mocks the UpdateProviderAPIKey method.
	UpdateProviderAPIKeyFunc func(id int, apiKey string) error

	// calls tracks calls to the methods.
	calls struct {
		// CreateCodexAccount holds details about calls to the CreateCodexAccount method.
		CreateCodexAccount []struct {
			// A is the a argument value.
			A *config.CodexAccount
		}
		// CreateProviderFromSite holds details about calls to the CreateProviderFromSite method.
		CreateProviderFromSite []struct {
			// SiteID is the siteID argument value.
			SiteID int
			// NameOverride is the nameOverride argument value.
			NameOverride string
			// ApiKey is the apiKey argument value.
			ApiKey string
			// OauthJSON is the oauthJSON argument value.
			OauthJSON json.RawMessage
		}
		// DeleteCodexAccount holds details about calls to the DeleteCodexAccount method.
		DeleteCodexAccount []struct {
			// ID is the id argument value.
			ID int
		}
		// DeleteProvider holds details about calls to the DeleteProvider method.
		DeleteProvider []struct {
			// ID is the id argument value.
			ID int
		}
		// FindCodexAccountByProviderID holds details about calls to the FindCodexAccountByProviderID method.
		FindCodexAccountByProviderID []struct {
			// ProviderID is the providerID argument value.
			ProviderID int
		}
		// GetCodexAccount holds details about calls to the GetCodexAccount method.
		GetCodexAccount []struct {
			// ID is the id argument value.
			ID int
		}
		// GetCodexAccountByAccountID holds details about calls to the GetCodexAccountByAccountID method.
		GetCodexAccountByAccountID []struct {
			// AccountID is the accountID argument value.
			AccountID string
		}
		// GetProviderAPIKey holds details about calls to the GetProviderAPIKey method.
		GetProviderAPIKey []struct {
			// ID is the id argument value.
			ID int
		}
		// ListCodexAccounts holds details about calls to the ListCodexAccounts method.
		ListCodexAccounts []struct {
		}
		// UpdateCodexAccount holds details about calls to the UpdateCodexAccount method.
		UpdateCodexAccount []struct {
			// A is the a argument value.
			A *config.CodexAccount
		}
		// UpdateCodexAccountHealth holds details about calls to the UpdateCodexAccountHealth method.
		UpdateCodexAccountHealth []struct {
			// ID is the id argument value.
			ID int
		}
		// UpdateCodexAccountRefresh holds details about calls to the UpdateCodexAccountRefresh method.
		UpdateCodexAccountRefresh []struct {
			// ID is the id argument value.
			ID int
		}
		// UpdateCodexAccountStatus holds details about calls to the UpdateCodexAccountStatus method.
		UpdateCodexAccountStatus []struct {
			// ID is the id argument value.
			ID int
			// Status is the status argument value.
			Status string
			// ErrorMsg is the errorMsg argument value.
			ErrorMsg string
		}
		// UpdateProviderAPIKey holds details about calls to the UpdateProviderAPIKey method.
		UpdateProviderAPIKey []struct {
			// ID is the id argument value.
			ID int
			// ApiKey is the apiKey argument value.
			ApiKey string
		}
	}
	lockCreateCodexAccount           sync.RWMutex
	lockCreateProviderFromSite       sync.RWMutex
	lockDeleteCodexAccount           sync.RWMutex
	lockDeleteProvider               sync.RWMutex
	lockFindCodexAccountByProviderID sync.RWMutex
	lockGetCodexAccount              sync.RWMutex
	lockGetCodexAccountByAccountID   sync.RWMutex
	lockGetProviderAPIKey            sync.RWMutex
	lockListCodexAccounts            sync.RWMutex
	lockUpdateCodexAccount           sync.RWMutex
	lockUpdateCodexAccountHealth     sync.RWMutex
	lockUpdateCodexAccountRefresh    sync.RWMutex
	lockUpdateCodexAccountStatus     sync.RWMutex
	lockUpdateProviderAPIKey         sync.RWMutex
}

// CreateCodexAccount calls CreateCodexAccountFunc.
func (mock *RegistryStoreMock) CreateCodexAccount(a *config.CodexAccount) error {
	if mock.CreateCodexAccountFunc == nil {
		panic("RegistryStoreMock.CreateCodexAccountFunc: method is nil but RegistryStore.CreateCodexAccount was just called")
	}
	callInfo := struct {
		A *config.CodexAccount
	}{
		A: a,
	}
	mock.lockCreateCodexAccount.Lock()
	mock.calls.CreateCodexAccount = append(mock.calls.CreateCodexAccount, callInfo)
	mock.lockCreateCodexAccount.Unlock()
	return mock.CreateCodexAccountFunc(a)
}

// CreateCodexAccountCalls gets all the calls that were made to CreateCodexAccount.
// Check the length with:
//
//	len(mockedRegistryStore.CreateCodexAccountCalls())
func (mock *RegistryStoreMock) CreateCodexAccountCalls() []struct {
	A *config.CodexAccount
} {
	var calls []struct {
		A *config.CodexAccount
	}
	mock.lockCreateCodexAccount.RLock()
	calls = mock.calls.CreateCodexAccount
	mock.lockCreateCodexAccount.RUnlock()
	return calls
}

// CreateProviderFromSite calls CreateProviderFromSiteFunc.
func (mock *RegistryStoreMock) CreateProviderFromSite(siteID int, nameOverride string, apiKey string, oauthJSON json.RawMessage) (*config.Provider, int, error) {
	if mock.CreateProviderFromSiteFunc == nil {
		panic("RegistryStoreMock.CreateProviderFromSiteFunc: method is nil but RegistryStore.CreateProviderFromSite was just called")
	}
	callInfo := struct {
		SiteID       int
		NameOverride string
		ApiKey       string
		OauthJSON    json.RawMessage
	}{
		SiteID:       siteID,
		NameOverride: nameOverride,
		ApiKey:       apiKey,
		OauthJSON:    oauthJSON,
	}
	mock.lockCreateProviderFromSite.Lock()
	mock.calls.CreateProviderFromSite = append(mock.calls.CreateProviderFromSite, callInfo)
	mock.lockCreateProviderFromSite.Unlock()
	return mock.CreateProviderFromSiteFunc(siteID, nameOverride, apiKey, oauthJSON)
}

// CreateProviderFromSiteCalls gets all the calls that were made to CreateProviderFromSite.
// Check the length with:
//
//	len(mockedRegistryStore.CreateProviderFromSiteCalls())
func (mock *RegistryStoreMock) CreateProviderFromSiteCalls() []struct {
	SiteID       int
	NameOverride string
	ApiKey       string
	OauthJSON    json.RawMessage
} {
	var calls []struct {
		SiteID       int
		NameOverride string
		ApiKey       string
		OauthJSON    json.RawMessage
	}
	mock.lockCreateProviderFromSite.RLock()
	calls = mock.calls.CreateProviderFromSite
	mock.lockCreateProviderFromSite.RUnlock()
	return calls
}

// DeleteCodexAccount calls DeleteCodexAccountFunc.
func (mock *RegistryStoreMock) DeleteCodexAccount(id int) error {
	if mock.DeleteCodexAccountFunc == nil {
		panic("RegistryStoreMock.DeleteCodexAccountFunc: method is nil but RegistryStore.DeleteCodexAccount was just called")
	}
	callInfo := struct {
		ID int
	}{
		ID: id,
	}
	mock.lockDeleteCodexAccount.Lock()
	mock.calls.DeleteCodexAccount = append(mock.calls.DeleteCodexAccount, callInfo)
	mock.lockDeleteCodexAccount.Unlock()
	return mock.DeleteCodexAccountFunc(id)
}

// DeleteCodexAccountCalls gets all the calls that were made to DeleteCodexAccount.
// Check the length with:
//
//	len(mockedRegistryStore.DeleteCodexAccountCalls())
func (mock *RegistryStoreMock) DeleteCodexAccountCalls() []struct {
	ID int
} {
	var calls []struct {
		ID int
	}
	mock.lockDeleteCodexAccount.RLock()
	calls = mock.calls.DeleteCodexAccount
	mock.lockDeleteCodexAccount.RUnlock()
	return calls
}

// DeleteProvider calls DeleteProviderFunc.
func (mock *RegistryStoreMock) DeleteProvider(id int) error {
	if mock.DeleteProviderFunc == nil {
		panic("RegistryStoreMock.DeleteProviderFunc: method is nil but RegistryStore.DeleteProvider was just called")
	}
	callInfo := struct {
		ID int
	}{
		ID: id,
	}
	mock.lockDeleteProvider.Lock()
	mock.calls.DeleteProvider = append(mock.calls.DeleteProvider, callInfo)
	mock.lockDeleteProvider.Unlock()
	return mock.DeleteProviderFunc(id)
}

// DeleteProviderCalls gets all the calls that were made to DeleteProvider.
// Check the length with:
//
//	len(mockedRegistryStore.DeleteProviderCalls())
func (mock *RegistryStoreMock) DeleteProviderCalls() []struct {
	ID int
} {
	var calls []struct {
		ID int
	}
	mock.lockDeleteProvider.RLock()
	calls = mock.calls.DeleteProvider
	mock.lockDeleteProvider.RUnlock()
	return calls
}

// FindCodexAccountByProviderID calls FindCodexAccountByProviderIDFunc.
func (mock *RegistryStoreMock) FindCodexAccountByProviderID(providerID int) (*config.CodexAccount, error) {
	if mock.FindCodexAccountByProviderIDFunc == nil {
		panic("RegistryStoreMock.FindCodexAccountByProviderIDFunc: method is nil but RegistryStore.FindCodexAccountByProviderID was just called")
	}
	callInfo := struct {
		ProviderID int
	}{
		ProviderID: providerID,
	}
	mock.lockFindCodexAccountByProviderID.Lock()
	mock.calls.FindCodexAccountByProviderID = append(mock.calls.FindCodexAccountByProviderID, callInfo)
	mock.lockFindCodexAccountByProviderID.Unlock()
	return mock.FindCodexAccountByProviderIDFunc(providerID)
}

// FindCodexAccountByProviderIDCalls gets all the calls that were made to FindCodexAccountByProviderID.
// Check the length with:
//
//	len(mockedRegistryStore.FindCodexAccountByProviderIDCalls())
func (mock *RegistryStoreMock) FindCodexAccountByProviderIDCalls() []struct {
	ProviderID int
} {
	var calls []struct {
		ProviderID int
	}
	mock.lockFindCodexAccountByProviderID.RLock()
	calls = mock.calls.FindCodexAccountByProviderID
	mock.lockFindCodexAccountByProviderID.RUnlock()
	return calls
}

// GetCodexAccount calls GetCodexAccountFunc.
func (mock *RegistryStoreMock) GetCodexAccount(id int) (*config.CodexAccount, error) {
	if mock.GetCodexAccountFunc == nil {
		panic("RegistryStoreMock.GetCodexAccountFunc: method is nil but RegistryStore.GetCodexAccount was just called")
	}
	callInfo := struct {
		ID int
	}{
		ID: id,
	}
	mock.lockGetCodexAccount.Lock()
	mock.calls.GetCodexAccount = append(mock.calls.GetCodexAccount, callInfo)
	mock.lockGetCodexAccount.Unlock()
	return mock.GetCodexAccountFunc(id)
}

// GetCodexAccountCalls gets all the calls that were made to GetCodexAccount.
// Check the length with:
//
//	len(mockedRegistryStore.GetCodexAccountCalls())
func (mock *RegistryStoreMock) GetCodexAccountCalls() []struct {
	ID int
} {
	var calls []struct {
		ID int
	}
	mock.lockGetCodexAccount.RLock()
	calls = mock.calls.GetCodexAccount
	mock.lockGetCodexAccount.RUnlock()
	return calls
}

// GetCodexAccountByAccountID calls GetCodexAccountByAccountIDFunc.
func (mock *RegistryStoreMock) GetCodexAccountByAccountID(accountID string) (*config.CodexAccount, error) {
	if mock.GetCodexAccountByAccountIDFunc == nil {
		panic("RegistryStoreMock.GetCodexAccountByAccountIDFunc: method is nil but RegistryStore.GetCodexAccountByAccountID was just called")
	}
	callInfo := struct {
		AccountID string
	}{
		AccountID: accountID,
	}
	mock.lockGetCodexAccountByAccountID.Lock()
	mock.calls.GetCodexAccountByAccountID = append(mock.calls.GetCodexAccountByAccountID, callInfo)
	mock.lockGetCodexAccountByAccountID.Unlock()
	return mock.GetCodexAccountByAccountIDFunc(accountID)
}

// GetCodexAccountByAccountIDCalls gets all the calls that were made to GetCodexAccountByAccountID.
// Check the length with:
//
//	len(mockedRegistryStore.GetCodexAccountByAccountIDCalls())
func (mock *RegistryStoreMock) GetCodexAccountByAccountIDCalls() []struct {
	AccountID string
} {
	var calls []struct {
		AccountID string
	}
	mock.lockGetCodexAccountByAccountID.RLock()
	calls = mock.calls.GetCodexAccountByAccountID
	mock.lockGetCodexAccountByAccountID.RUnlock()
	return calls
}

// GetProviderAPIKey calls GetProviderAPIKeyFunc.
func (mock *RegistryStoreMock) GetProviderAPIKey(id int) (string, error) {
	if mock.GetProviderAPIKeyFunc == nil {
		panic("RegistryStoreMock.GetProviderAPIKeyFunc: method is nil but RegistryStore.GetProviderAPIKey was just called")
	}
	callInfo := struct {
		ID int
	}{
		ID: id,
	}
	mock.lockGetProviderAPIKey.Lock()
	mock.calls.GetProviderAPIKey = append(mock.calls.GetProviderAPIKey, callInfo)
	mock.lockGetProviderAPIKey.Unlock()
	return mock.GetProviderAPIKeyFunc(id)
}

// GetProviderAPIKeyCalls gets all the calls that were made to GetProviderAPIKey.
// Check the length with:
//
//	len(mockedRegistryStore.GetProviderAPIKeyCalls())
func (mock *RegistryStoreMock) GetProviderAPIKeyCalls() []struct {
	ID int
} {
	var calls []struct {
		ID int
	}
	mock.lockGetProviderAPIKey.RLock()
	calls = mock.calls.GetProviderAPIKey
	mock.lockGetProviderAPIKey.RUnlock()
	return calls
}

// ListCodexAccounts calls ListCodexAccountsFunc.
func (mock *RegistryStoreMock) ListCodexAccounts() ([]config.CodexAccount, error) {
	if mock.ListCodexAccountsFunc == nil {
		panic("RegistryStoreMock.ListCodexAccountsFunc: method is nil but RegistryStore.ListCodexAccounts was just called")
	}
	callInfo := struct {
	}{}
	mock.lockListCodexAccounts.Lock()
	mock.calls.ListCodexAccounts = append(mock.calls.ListCodexAccounts, callInfo)
	mock.lockListCodexAccounts.Unlock()
	return mock.ListCodexAccountsFunc()
}

// ListCodexAccountsCalls gets all the calls that were made to ListCodexAccounts.
// Check the length with:
//
//	len(mockedRegistryStore.ListCodexAccountsCalls())
func (mock *RegistryStoreMock) ListCodexAccountsCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockListCodexAccounts.RLock()
	calls = mock.calls.ListCodexAccounts
	mock.lockListCodexAccounts.RUnlock()
	return calls
}

// UpdateCodexAccount calls UpdateCodexAccountFunc.
func (mock *RegistryStoreMock) UpdateCodexAccount(a *config.CodexAccount) error {
	if mock.UpdateCodexAccountFunc == nil {
		panic("RegistryStoreMock.UpdateCodexAccountFunc: method is nil but RegistryStore.UpdateCodexAccount was just called")
	}
	callInfo := struct {
		A *config.CodexAccount
	}{
		A: a,
	}
	mock.lockUpdateCodexAccount.Lock()
	mock.calls.UpdateCodexAccount = append(mock.calls.UpdateCodexAccount, callInfo)
	mock.lockUpdateCodexAccount.Unlock()
	return mock.UpdateCodexAccountFunc(a)
}

// UpdateCodexAccountCalls gets all the calls that were made to UpdateCodexAccount.
// Check the length with:
//
//	len(mockedRegistryStore.UpdateCodexAccountCalls())
func (mock *RegistryStoreMock) UpdateCodexAccountCalls() []struct {
	A *config.CodexAccount
} {
	var calls []struct {
		A *config.CodexAccount
	}
	mock.lockUpdateCodexAccount.RLock()
	calls = mock.calls.UpdateCodexAccount
	mock.lockUpdateCodexAccount.RUnlock()
	return calls
}

// UpdateCodexAccountHealth calls UpdateCodexAccountHealthFunc.
func (mock *RegistryStoreMock) UpdateCodexAccountHealth(id int) error {
	if mock.UpdateCodexAccountHealthFunc == nil {
		panic("RegistryStoreMock.UpdateCodexAccountHealthFunc: method is nil but RegistryStore.UpdateCodexAccountHealth was just called")
	}
	callInfo := struct {
		ID int
	}{
		ID: id,
	}
	mock.lockUpdateCodexAccountHealth.Lock()
	mock.calls.UpdateCodexAccountHealth = append(mock.calls.UpdateCodexAccountHealth, callInfo)
	mock.lockUpdateCodexAccountHealth.Unlock()
	return mock.UpdateCodexAccountHealthFunc(id)
}

// UpdateCodexAccountHealthCalls gets all the calls that were made to UpdateCodexAccountHealth.
// Check the length with:
//
//	len(mockedRegistryStore.UpdateCodexAccountHealthCalls())
func (mock *RegistryStoreMock) UpdateCodexAccountHealthCalls() []struct {
	ID int
} {
	var calls []struct {
		ID int
	}
	mock.lockUpdateCodexAccountHealth.RLock()
	calls = mock.calls.UpdateCodexAccountHealth
	mock.lockUpdateCodexAccountHealth.RUnlock()
	return calls
}

// UpdateCodexAccountRefresh calls UpdateCodexAccountRefreshFunc.
func (mock *RegistryStoreMock) UpdateCodexAccountRefresh(id int) error {
	if mock.UpdateCodexAccountRefreshFunc == nil {
		panic("RegistryStoreMock.UpdateCodexAccountRefreshFunc: method is nil but RegistryStore.UpdateCodexAccountRefresh was just called")
	}
	callInfo := struct {
		ID int
	}{
		ID: id,
	}
	mock.lockUpdateCodexAccountRefresh.Lock()
	mock.calls.UpdateCodexAccountRefresh = append(mock.calls.UpdateCodexAccountRefresh, callInfo)
	mock.lockUpdateCodexAccountRefresh.Unlock()
	return mock.UpdateCodexAccountRefreshFunc(id)
}

// UpdateCodexAccountRefreshCalls gets all the calls that were made to UpdateCodexAccountRefresh.
// Check the length with:
//
//	len(mockedRegistryStore.UpdateCodexAccountRefreshCalls())
func (mock *RegistryStoreMock) UpdateCodexAccountRefreshCalls() []struct {
	ID int
} {
	var calls []struct {
		ID int
	}
	mock.lockUpdateCodexAccountRefresh.RLock()
	calls = mock.calls.UpdateCodexAccountRefresh
	mock.lockUpdateCodexAccountRefresh.RUnlock()
	return calls
}

// UpdateCodexAccountStatus calls UpdateCodexAccountStatusFunc.
func (mock *RegistryStoreMock) UpdateCodexAccountStatus(id int, status string, errorMsg string) error {
	if mock.UpdateCodexAccountStatusFunc == nil {
		panic("RegistryStoreMock.UpdateCodexAccountStatusFunc: method is nil but RegistryStore.UpdateCodexAccountStatus was just called")
	}
	callInfo := struct {
		ID       int
		Status   string
		ErrorMsg string
	}{
		ID:       id,
		Status:   status,
		ErrorMsg: errorMsg,
	}
	mock.lockUpdateCodexAccountStatus.Lock()
	mock.calls.UpdateCodexAccountStatus = append(mock.calls.UpdateCodexAccountStatus, callInfo)
	mock.lockUpdateCodexAccountStatus.Unlock()
	return mock.UpdateCodexAccountStatusFunc(id, status, errorMsg)
}

// UpdateCodexAccountStatusCalls gets all the calls that were made to UpdateCodexAccountStatus.
// Check the length with:
//
//	len(mockedRegistryStore.UpdateCodexAccountStatusCalls())
func (mock *RegistryStoreMock) UpdateCodexAccountStatusCalls() []struct {
	ID       int
	Status   string
	ErrorMsg string
} {
	var calls []struct {
		ID       int
		Status   string
		ErrorMsg string
	}
	mock.lockUpdateCodexAccountStatus.RLock()
	calls = mock.calls.UpdateCodexAccountStatus
	mock.lockUpdateCodexAccountStatus.RUnlock()
	return calls
}

// UpdateProviderAPIKey calls UpdateProviderAPIKeyFunc.
func (mock *RegistryStoreMock) UpdateProviderAPIKey(id int, apiKey string) error {
	if mock.UpdateProviderAPIKeyFunc == nil {
		panic("RegistryStoreMock.UpdateProviderAPIKeyFunc: method is nil but RegistryStore.UpdateProviderAPIKey was just called")
	}
	callInfo := struct {
		ID     int
		ApiKey string
	}{
		ID:     id,
		ApiKey: apiKey,
	}
	mock.lockUpdateProviderAPIKey.Lock()
	mock.calls.UpdateProviderAPIKey = append(mock.calls.UpdateProviderAPIKey, callInfo)
	mock.lockUpdateProviderAPIKey.Unlock()
	return mock.UpdateProviderAPIKeyFunc(id, apiKey)
}

// UpdateProviderAPIKeyCalls gets all the calls that were made to UpdateProviderAPIKey.
// Check the length with:
//
//	len(mockedRegistryStore.UpdateProviderAPIKeyCalls())
func (mock *RegistryStoreMock) UpdateProviderAPIKeyCalls() []struct {
	ID     int
	ApiKey string
} {
	var calls []struct {
		ID     int
		ApiKey string
	}
	mock.lockUpdateProviderAPIKey.RLock()
	calls = mock.calls.UpdateProviderAPIKey
	mock.lockUpdateProviderAPIKey.RUnlock()
	return calls
}
