// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package codexauth

import (
	"context"
	"sync"
)

// Ensure, that BrowserClientMock does implement BrowserClient.
// If this is not the case, regenerate this file with moq.
var _ BrowserClient = &BrowserClientMock{}

// BrowserClientMock is a mock implementation of BrowserClient.
//
//	func TestSomethingThatUsesBrowserClient(t *testing.T) {
//
//		// make and configure a mocked BrowserClient
//		mockedBrowserClient := &BrowserClientMock{
//			ClickFunc: func(ctx context.Context, selector string) error {
//				panic("mock out the Click method")
//			},
//			NavigateFunc: func(ctx context.Context, url string) error {
//				panic("mock out the Navigate method")
//			},
//			NewContextFunc: func(ctx context.Context) (context.Context, context.CancelFunc) {
//				panic("mock out the NewContext method")
//			},
//			SendKeysFunc: func(ctx context.Context, selector string, text string) error {
//				panic("mock out the SendKeys method")
//			},
//			WaitForSelectorFunc: func(ctx context.Context, selector string) error {
//				panic("mock out the WaitForSelector method")
//			},
//		}
//
//		// use mockedBrowserClient in code that requires BrowserClient
//		// and then make assertions.
//
//	}
type BrowserClientMock struct {
	// ClickFunc mocks the Click method.
	ClickFunc func(ctx context.Context, selector string) error

	// NavigateFunc mocks the Navigate method.
	NavigateFunc func(ctx context.Context, url string) error

	// NewContextFunc mocks the NewContext method.
	NewContextFunc func(ctx context.Context) (context.Context, context.CancelFunc)

	// SendKeysFunc mocks the SendKeys method.
	SendKeysFunc func(ctx context.Context, selector string, text string) error

	// WaitForSelectorFunc mocks the WaitForSelector method.
	WaitForSelectorFunc func(ctx context.Context, selector string) error

	// calls tracks calls to the methods.
	calls struct {
		// Click holds details about calls to the Click method.
		Click []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Selector is the selector argument value.
			Selector string
		}
		// Navigate holds details about calls to the Navigate method.
		Navigate []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// URL is the url argument value.
			URL string
		}
		// NewContext holds details about calls to the NewContext method.
		NewContext []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// SendKeys holds details about calls to the SendKeys method.
		SendKeys []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Selector is the selector argument value.
			Selector string
			// Text is the text argument value.
			Text string
		}
		// WaitForSelector holds details about calls to the WaitForSelector method.
		WaitForSelector []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Selector is the selector argument value.
			Selector string
		}
	}
	lockClick           sync.RWMutex
	lockNavigate        sync.RWMutex
	lockNewContext      sync.RWMutex
	lockSendKeys        sync.RWMutex
	lockWaitForSelector sync.RWMutex
}

// Click calls ClickFunc.
func (mock *BrowserClientMock) Click(ctx context.Context, selector string) error {
	if mock.ClickFunc == nil {
		panic("BrowserClientMock.ClickFunc: method is nil but BrowserClient.Click was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Selector string
	}{
		Ctx:      ctx,
		Selector: selector,
	}
	mock.lockClick.Lock()
	mock.calls.Click = append(mock.calls.Click, callInfo)
	mock.lockClick.Unlock()
	return mock.ClickFunc(ctx, selector)
}

// ClickCalls gets all the calls that were made to Click.
// Check the length with:
//
//	len(mockedBrowserClient.ClickCalls())
func (mock *BrowserClientMock) ClickCalls() []struct {
	Ctx      context.Context
	Selector string
} {
	var calls []struct {
		Ctx      context.Context
		Selector string
	}
	mock.lockClick.RLock()
	calls = mock.calls.Click
	mock.lockClick.RUnlock()
	return calls
}

// Navigate calls NavigateFunc.
func (mock *BrowserClientMock) Navigate(ctx context.Context, url string) error {
	if mock.NavigateFunc == nil {
		panic("BrowserClientMock.NavigateFunc: method is nil but BrowserClient.Navigate was just called")
	}
	callInfo := struct {
		Ctx context.Context
		URL string
	}{
		Ctx: ctx,
		URL: url,
	}
	mock.lockNavigate.Lock()
	mock.calls.Navigate = append(mock.calls.Navigate, callInfo)
	mock.lockNavigate.Unlock()
	return mock.NavigateFunc(ctx, url)
}

// NavigateCalls gets all the calls that were made to Navigate.
// Check the length with:
//
//	len(mockedBrowserClient.NavigateCalls())
func (mock *BrowserClientMock) NavigateCalls() []struct {
	Ctx context.Context
	URL string
} {
	var calls []struct {
		Ctx context.Context
		URL string
	}
	mock.lockNavigate.RLock()
	calls = mock.calls.Navigate
	mock.lockNavigate.RUnlock()
	return calls
}

// NewContext calls NewContextFunc.
func (mock *BrowserClientMock) NewContext(ctx context.Context) (context.Context, context.CancelFunc) {
	if mock.NewContextFunc == nil {
		panic("BrowserClientMock.NewContextFunc: method is nil but BrowserClient.NewContext was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockNewContext.Lock()
	mock.calls.NewContext = append(mock.calls.NewContext, callInfo)
	mock.lockNewContext.Unlock()
	return mock.NewContextFunc(ctx)
}

// NewContextCalls gets all the calls that were made to NewContext.
// Check the length with:
//
//	len(mockedBrowserClient.NewContextCalls())
func (mock *BrowserClientMock) NewContextCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockNewContext.RLock()
	calls = mock.calls.NewContext
	mock.lockNewContext.RUnlock()
	return calls
}

// SendKeys calls SendKeysFunc.
func (mock *BrowserClientMock) SendKeys(ctx context.Context, selector string, text string) error {
	if mock.SendKeysFunc == nil {
		panic("BrowserClientMock.SendKeysFunc: method is nil but BrowserClient.SendKeys was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Selector string
		Text     string
	}{
		Ctx:      ctx,
		Selector: selector,
		Text:     text,
	}
	mock.lockSendKeys.Lock()
	mock.calls.SendKeys = append(mock.calls.SendKeys, callInfo)
	mock.lockSendKeys.Unlock()
	return mock.SendKeysFunc(ctx, selector, text)
}

// SendKeysCalls gets all the calls that were made to SendKeys.
// Check the length with:
//
//	len(mockedBrowserClient.SendKeysCalls())
func (mock *BrowserClientMock) SendKeysCalls() []struct {
	Ctx      context.Context
	Selector string
	Text     string
} {
	var calls []struct {
		Ctx      context.Context
		Selector string
		Text     string
	}
	mock.lockSendKeys.RLock()
	calls = mock.calls.SendKeys
	mock.lockSendKeys.RUnlock()
	return calls
}

// WaitForSelector calls WaitForSelectorFunc.
func (mock *BrowserClientMock) WaitForSelector(ctx context.Context, selector string) error {
	if mock.WaitForSelectorFunc == nil {
		panic("BrowserClientMock.WaitForSelectorFunc: method is nil but BrowserClient.WaitForSelector was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Selector string
	}{
		Ctx:      ctx,
		Selector: selector,
	}
	mock.lockWaitForSelector.Lock()
	mock.calls.WaitForSelector = append(mock.calls.WaitForSelector, callInfo)
	mock.lockWaitForSelector.Unlock()
	return mock.WaitForSelectorFunc(ctx, selector)
}

// WaitForSelectorCalls gets all the calls that were made to WaitForSelector.
// Check the length with:
//
//	len(mockedBrowserClient.WaitForSelectorCalls())
func (mock *BrowserClientMock) WaitForSelectorCalls() []struct {
	Ctx      context.Context
	Selector string
} {
	var calls []struct {
		Ctx      context.Context
		Selector string
	}
	mock.lockWaitForSelector.RLock()
	calls = mock.calls.WaitForSelector
	mock.lockWaitForSelector.RUnlock()
	return calls
}
